/**
 * Generuje Mongo `collMod` commandy pre nastavenie `$jsonSchema` validátorov.
 *
 * Spustenie:
 *   pnpm --filter @sfz/shared-types run generate:mongo-validators
 *
 * Výstup:
 *   packages/shared-types/generated/mongo-validators.js
 *
 * Vygenerovaný súbor je **mongo shell skript**, ktorý nastaví validátory
 * na všetkých collections. Spúšťa sa cez:
 *   mongosh "$MONGO_URI" packages/shared-types/generated/mongo-validators.js
 *
 * V produkčnom prostredí toto robí migračný skript v `apps/api`, ktorý:
 * 1. Načíta `generated/json-schema.json`
 * 2. Pre každú collection zavolá `db.runCommand({ collMod, validator })`
 *
 * Tento standalone skript je primárne pre lokálny dev a CI overovanie.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const INPUT_PATH = resolve(__dirname, '..', 'generated', 'json-schema.json');
const OUTPUT_PATH = resolve(__dirname, '..', 'generated', 'mongo-validators.js');

/**
 * Mapovanie schémy → Mongo collection.
 * Pridaj nový záznam, keď pridáš novú entitu.
 */
const SCHEMA_TO_COLLECTION: Record<string, string> = {
  Asset: 'assets',
  Attachment: 'attachments',
  AuditLog: 'audit_log',
  Category: 'categories',
  Loan: 'loans',
  LoanProtocol: 'loan_protocols',
  LoanRequest: 'loan_requests',
  Location: 'locations',
  Notification: 'notifications',
  StockMovement: 'stock_movements',
  User: 'users',
};

interface JsonSchemaFile {
  definitions: Record<string, unknown>;
}

async function main(): Promise<void> {
  console.info('🔧 Generujem Mongo collMod commandy...');

  let raw: string;
  try {
    raw = await readFile(INPUT_PATH, 'utf-8');
  } catch {
    console.error(`❌ Súbor ${INPUT_PATH} neexistuje. Spusti najprv:`);
    console.error('   pnpm --filter @sfz/shared-types run generate:json-schema');
    process.exit(1);
  }

  const jsonSchema = JSON.parse(raw) as JsonSchemaFile;
  const definitions = jsonSchema.definitions;

  const commands: string[] = [
    '// Auto-generated by scripts/generate-mongo-validators.ts',
    '// DO NOT EDIT MANUALLY',
    `// Generated at: ${new Date().toISOString()}`,
    '',
    '// Spustenie: mongosh "$MONGO_URI" packages/shared-types/generated/mongo-validators.js',
    '',
    'print("🔧 Nastavujem $jsonSchema validátory...");',
    '',
  ];

  for (const [schemaName, collectionName] of Object.entries(SCHEMA_TO_COLLECTION)) {
    const schema = definitions[schemaName];
    if (!schema) {
      console.warn(`  ⚠️  Schéma ${schemaName} sa nenašla v JSON Schema výstupe, preskakujem.`);
      continue;
    }

    commands.push(
      `// === ${collectionName} ===`,
      `db.runCommand({`,
      `  collMod: ${JSON.stringify(collectionName)},`,
      `  validator: { $jsonSchema: ${JSON.stringify(schema)} },`,
      `  validationLevel: "strict",`,
      `  validationAction: "error"`,
      `});`,
      `print("  ✓ ${collectionName}");`,
      '',
    );

    console.info(`  ✓ ${collectionName} (${schemaName})`);
  }

  commands.push('print("\\n✅ Hotovo.");');

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, commands.join('\n'), 'utf-8');

  console.info(
    `\n✅ Vygenerovaných ${Object.keys(SCHEMA_TO_COLLECTION).length} commandov do ${OUTPUT_PATH}`,
  );
}

main().catch((err: unknown) => {
  console.error('❌ Generovanie zlyhalo:', err);
  process.exit(1);
});
